import os

MODULE="\nsettings.static_srv.production\n"

DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

LINODE_BUCKET = 'django-demos'
LINODE_BUCKET_REGION = 'us-southeast-1'

LINODE_BUCKET_ACCESS_KEY = os.environ.get("LINODE_BUCKET_ACCCESS_KEY")
LINODE_BUCKET_SECRET_KEY = os.environ.get("LINODE_BUCKET_SECRET_KEY")

AWS_S3_ENDPOINT_URL = f'https://{LINODE_BUCKET_REGION}.linodeobjects.com'
AWS_ACCESS_KEY_ID = LINODE_BUCKET_ACCESS_KEY
AWS_SECRET_ACCESS_KEY = LINODE_BUCKET_SECRET_KEY
AWS_S3_REGION_NAME = LINODE_BUCKET_REGION
AWS_S3_USE_SSL = True
AWS_STORAGE_BUCKET_NAME = LINODE_BUCKET
print(f"AWS_ACCESS_KEY_ID {AWS_ACCESS_KEY_ID} \nAWS_SECRET_ACCESS_KEY {AWS_SECRET_ACCESS_KEY} \nAWS_STORAGE_BUCKET_NAME {AWS_STORAGE_BUCKET_NAME}")