# Generated by Django 3.2.9 on 2021-12-12 07:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cfeblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfepost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='cfepost_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
