# Generated by Django 3.2.9 on 2022-02-05 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfeblog', '0002_cfepost_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfepost',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
